### PR TITLE
Added JPG support

### LINKED ISSUE #79: Add JPG to Imageload
Not sure if imageload has JPG capability.  RTD is lacking details.  Would very much appreciate a JPG simpletest example.

### PR DESCRIPTION
**Pull request by ch4nsuk3**
Fixes #79 

Adds JPG support via calls to the [jpegio](https://docs.circuitpython.org/en/latest/shared-bindings/jpegio/index.html) library, allowing use of consistent code without having to switch back and forth between the two libraries directly. This is the easiest way to do it, as trying to create a JPG decoder in python is never going to be as efficient as jpegio as it and the library it relies upon, [tjpgd](https://github.com/adafruit/circuitpython/tree/main/lib/tjpgd), are coded in C and are well optimized. Progressive JPG images are not supported.

I originally was going to implement a check for the flags which indicate what encoding method is used by scanning the header data, as other classes in this library do, in order to allow for raising an error without having to call jpegio at all. However these flags come after exif data, which can run quite long. This means it could potentially require quite a bit of chewing through a file to get to the needed flags, something jpegio will do much quicker.

I intentionally kept the arguments provided to `jpegio.decode` minimal. The extra arguments are primarily for blit operations and anyone needing those options is likely better served by using jpegio directly.

The load function returns a Bitmap and ColorConverter

Changes to the __init__ file are to check for the flags indicating a JPG image, then calling for the load function if so.

I have also included a simpletest showcasing usage. I have provided a sample image as well, a 48x48px image of my cat, done in a posterized style, along with a license document using the MIT license. I understand if you would prefer to use a different image as the test image.

### CODE REVIEW

**Comment by tannewt** [comment]
> I have also included a simpletest showcasing usage. I have provided a sample image as well, a 48x48px image of my cat, done in a posterized style, along with a license document using the MIT license. I understand if you would prefer to use a different image as the test image.

Pictures of cats are always welcome. Thanks!

**Review by tannewt — COMMENTED** [review]
Great idea! This is helpful. I bet you need to setup pre-commit locally: https://learn.adafruit.com/improve-your-code-with-pylint/check-your-code-with-pre-commit

**Comment by ch4nsuk3** [comment]
Sorry for that, pre-commit was choking on me. I have Python 3.12 installed and pre-commit was choking because I am on Python 3.12. I wound up setting up PyCharm to run pylint and black for me.

**Review by tannewt — APPROVED** [review]
Thank you! Looks good. Sorry about the 3.12 issues. We're in the process of moving over ourselves.

**Pull request merged**
