### PR TITLE
Set bitmap and palette to have default values

### PR DESCRIPTION
**Pull request by dherrada**
@caternuson My only concern is that this has us importing displayio more than once.

### CODE REVIEW

**Comment by caternuson** [comment]
You could leave the parameter defaults as `None` and then check for `None` in the constructor and import as needed.

It might be worth having more discussion over in the issue thread before PR'ing. There may be reasons why my suggestion isn't a good idea? I'm not sure.

**Comment by dherrada** [comment]
Good point

**Comment by dherrada** [comment]
@caternuson I've made the changes you've suggested, but I'm totally fine waiting for this to be discussed before a decision is made.

**Comment by caternuson** [comment]
OK, based on issue discussion, seems like no reason to keep pursuing this :)

The next thing I'd suggest is surrounding the displayio import with `try/except` block. So for setups that don't have displayio, the import will fail, you can catch that, and then just revert to the previous behavior.

**Comment by kattni** [comment]
@caternuson Dylan is away for a bit. Do you mind taking over this PR?

**Comment by caternuson** [comment]
@kattni Sure, hopefully just a few minor things, which I just pushed. I removed me as reviewer and opened it up to CP librarians.

**Comment by kattni** [comment]
@FoamyGuy Please test this PR and if you approve, feel free to merge. Thanks!

**Pull request merged**
