### PR TITLE
Adds support for RLE compression to BMPs

### PR DESCRIPTION
**Pull request by fionawhim**
Fixes adafruit/Adafruit_CircuitPython_ImageLoad#20

RLE compression is allowed on 4-bit and 8-bit BMP images. This commit adds
handling for compression levels 1 and 2.

It adds 2 tiny test files for the 4-bit and 8-bit depths, since the
algorithm differs slightly between them. It also includes a version
of the color_wheel.bmp encoded with 8-bit RLE. I cut the image in half
horizontally so that it would load on the PyGamer, which couldn't
allocate the full Bitmap (presumably due to heap fragmentation).

### CODE REVIEW

**Comment by fionawhim** [comment]
The code is working AFAICT. The build failure is in the linting stuff which I don’t know how to address.

**Comment by ladyada** [comment]
@PaintYourDragon taggin you as an FYI if we want to support RLE in bmpdraw

**Comment by ladyada** [comment]
hiya yep pylint is a little sad
https://travis-ci.com/adafruit/Adafruit_CircuitPython_ImageLoad/builds/123582501#L548
but these are not too bad:
remove trailing whitespace with your editor
for line too long, you can split the line into two
for the other complatints, you could try to refactor your code to have a helper function OR you can disable pylint complatins on those lines if its not worthwhile refactoring

**Comment by fionawhim** [comment]
Awesome. I should be able to sort that out very soon.

**Comment by fionawhim** [comment]
OK, build passing now!

**Comment by ladyada** [comment]
yay pardon for the delay - this is now released on pypi!

**Pull request merged**
