### PR TITLE
Use ruff. add optional different format types to png example

### PR DESCRIPTION
**Pull request by FoamyGuy**
Changes the repository to use Ruff instead of pylint / black. 

Also adds 3 new png image files that have formats with support added by recent PRs and some comented out lines in the png example for the user to test with them if they wish.

### CODE REVIEW

**Comment by FoamyGuy** [comment]
I am investigating the actions failure. it appears that mpy-cross has taken issue with something.

**Comment by FoamyGuy** [comment]
Okay, the root of that issue was that currently used version of mpy-cross (8.2.0) does not support the f-string syntax with `!r` repr substitutions which ruff wanted to use by default:
```
f"Unsupported image format {magic_number!r}"
```
For now we need to use this syntax instead in order to make mpy-cross happy:
```
"Unsupported image format {!r}".format(magic_number))
```

It's possible that some future version of mpy-cross would support this in which case we could remove the exclusion from here and use the f-string syntax. I noticed there are newer mpy-cross

**Comment by FoamyGuy** [comment]
I tested and confirmed that the f-string syntax does work with mpy-cross 9.x. So, after we make a final 8.x bundle we could switch back to the f-string syntax and remove the exclusion.

**Review by tannewt — CHANGES_REQUESTED** [review]
I don't think the actual image files are included. I only see the licenses for them. Everything else looks good. Thanks!

**Comment by FoamyGuy** [comment]
Whoops, thank you. Added the images with the latest commit.

**Review by tannewt — CHANGES_REQUESTED** [review]
My browser isn't opening the image files. Is that expected?

**Comment by FoamyGuy** [comment]
Nice catch, I think the image files are corrupted or something. I'll look into more later today and try to get them fixed. 

I'm not entirely sure of the cause though. The originals that exist in my local copy of the repo on this branch seem to be functional, I can view them in my OS basic image viewer app. When I download them from Github I end up with files that are different. I compared sha256 sum of one of the images and the downloaded one differs from the one in my local repo. The downloaded one does not render in my OS basic image viewer either.

**Comment by FoamyGuy** [comment]
After some experimentation on another branch and a few tries committing to here I think I've figured this out. The `.gitattributes` file that was added configuring the eol option seems to be corrupting those PNG files. 

I noticed that the broken version of the smallest image was exactly 1 byte smaller than the working version and made a guess that the difference was due to a line ending difference. I'm not exactly sure how to compare the raw bytes within the files but in another branch I tested the theory by removing that file then removing and re-adding the images. After doing that they were working correctly on the Github pages in the browser, and when I download them from Github they also work in my image viewer app. I also confirmed the sha256 hash of the downloaded file now matches the one in my local copy of the repo.

The most recent commits to this branch remove the gitattributes file and then remove and re-add the images. They appear to be functioning correctly for me on this branch now as well.

**Review by tannewt — APPROVED** [review]
Thanks! Nice job figuring out the issue.

**Pull request merged**
