### PR TITLE
Working P1-P6 formats

### PR DESCRIPTION
**Pull request by matt-land**
Opening to see what Travis says

### CODE REVIEW

**Comment by tannewt** [comment]
Thank you! Please ping me when it's ready for review.

**Comment by matt-land** [comment]
Scott, 
It's still failing pylint, but I'd like to do review round #1 before I fix those last few things.

**Comment by matt-land** [comment]
I had to rework some things to pass pylint and fix a bug. If this looks good, I'll merge.

 @crookedstorm @Riddlerat

**Comment by crookedstorm** [comment]
@matt-land Looks great!  Thank you for cleaning up all our noodling at the end.  ❤️

**Pull request merged**
